Actor 007:
  State A:
    Message Name X:
      IF:
        Condition: [Message Name X: fieldY, <=: 25]
      THEN:
        Scala: scala code block goes here
        Goto: State B
    Message Name Y:
      Goto: State B
  State B:
    RegEx(*):
      Fn_Send: TerminatorActor